import { Geist, Geist_Mono } from "next/font/google";
import Link from 'next/link';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
      >
        <nav className="bg-white shadow mb-6">
          <div className="container mx-auto px-4 py-3 flex justify-between items-center lg:max-w-screen-lg">
            <span className="font-bold text-xl text-gray-800">Invest App</span>
            <div className="space-x-4">
              <Link href="/" className="text-gray-700 hover:text-blue-600">Home</Link>
              <Link href="/about" className="text-gray-700 hover:text-blue-600">About</Link>
            </div>
          </div>
        </nav>
        <div className="container min-h-screen mx-auto lg:max-w-screen-lg">
          {children}
        </div>
      </body>
    </html>
  );
}
